### ISSUE TITLE
feedback voortgang 2

### ISSUE THREAD

**Issue by SamSlotemaker** [marijnkamerbeek/Frontenddevelopment#1]
Ik lees dat je moeite hebt met flexbox en alignment, plak dit stukje code eens in je css en kijk goed naar wat er gebeurt. Flexbox zet items simpelweg naast elkaar. Wat ik hier doe is: alle items in navsection naast elkaar zetten en zeggen dat ze naar een volgende regel mogen springen wanneer er geen ruimte meer is.
Vervolgens, mogen alle items in de a ook naast elkaar staan (de img en tekst) en met align-items: center; worden deze op een horizontale lijn mooi gecentreert. De magins en paddings zijn simpelweg om de ruimte er tussen wat netter te maken. Kijk ook eens goed in de inspector en vink dingen eens aan en uit om goed te kijken wat de regels doen. 

```css
#navsection {
    display: flex;
    flex-wrap: wrap;
}

#navsection a {
    display: flex;
    padding: .5em;
    align-items: center
}
#navsection a img {    
    padding: 0;
    margin-right: .5em
}
```

Probeer verder geen div's te gebruiken om secties aan te duiden daarvoor heb je namelijk simpelweg de <section> 

wel zou je bijvoorbeeld een div kunnen gebruiken voor de blauwe img overlays. Nu is de blauwe achtergrond namelijk over de hele section, terwijl je deze alleen over de img heen wilt. Je kunt een div maken met precies dezelfde groottes als je img's en deze met position absolute vervolgens over de afbeeldingen heenzetten. 

Heading structuur lijkt veelal goed te gaan, maar kijk toch nog even goed door je sections en articles want er missen er nog wel een paar. 
Denk ook even goed aan het verschil tussen een anchor en een button. een button triggert iets op dezelfde pagina, bijvoorbeeld een hamburger menu, een like knop, etc. Een anchor linkt naar een andere pagina.
